### ISSUE TITLE
bug during pretrain

### ISSUE THREAD

**Issue by SANJINGSHOU14** [xinyu1205/recognize-anything#123]
Hello, I am training the RAM model, this is part of my "pretrain.yaml"

```
# size of vit model; base or large
vit: 'swin_l'
vit_grad_ckpt: False
vit_ckpt_layer: 0

image_size: 384
batch_size: 8

# optimizer
weight_decay: 0.05
init_lr: 1e-4
min_lr: 5e-7
warmup_lr: 5e-7
lr_decay_rate: 0.9
max_epoch: 500
warmup_steps: 3000

class_num: 4585
```
the problem is that when I set the image size as 384, and it will throw error in the "clip.encode_image()" as follow:

```
Traceback (most recent call last):
  File "pretrain.py", line 310, in <module>
    main(args, config)
  File "pretrain.py", line 262, in main
    train_stats = train_ram(model, data_loader, optimizer, epoch, device, config, model_clip) 
  File "pretrain.py", line 118, in train_ram
    clip_image_feature = model_clip.encode_image(image)
  File "/opt/conda/lib/python3.8/site-packages/clip/model.py", line 342, in encode_image
    return self.visual(image.type(self.dtype))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/clip/model.py", line 229, in forward
    x = x + self.positional_embedding.to(x.dtype)
RuntimeError: The size of tensor a (577) must match the size of tensor b (197) at non-singleton dimension 1
```

 it seems that the pretrained CLIP model receive the image size is 224x224, what should I do if i want to train the model with image size at 384?

**Comment by xinyu1205** [comment]
The default input size for pre-training is 224 * 224, you can refer to finetune. py

**Comment by SANJINGSHOU14** [comment]
@xinyu1205 Thanks for your answer. So, the correct process is I use `pretrain.py` with a 224x224 resolution to get a base model and then use `finetune.py` to retrain the model with a 384x384 resolution?

**Comment by xinyu1205** [comment]
Correct!

**Comment by SANJINGSHOU14** [comment]
> 正确的！

**Comment by SANJINGSHOU14** [comment]
> Correct!

Thanks again for your answer.
