### ISSUE TITLE
RuntimeError: checkpoint url or path is invalid

### ISSUE THREAD

**Issue by wkrrya** [xinyu1205/recognize-anything#167]
Hi, when I try to run the ram_plus model I get a RuntimeError. Could someone please assist me with this?
python3 inference_ram_plus.py  --image images/demo/demo1.jpg --pretrained pretrained/ram_plus_swin_large_14m.pth

--------------
pretrained/ram_plus_swin_large_14m.pth
--------------
Traceback (most recent call last):
  File "RAM_test/recognize-anything/inference_ram_plus.py", line 43, in <module>
    model = ram_plus(pretrained=args.pretrained,
  File "RAM_test/recognize-anything/ram/models/ram_plus.py", line 398, in ram_plus
    model, msg = load_checkpoint_swinlarge(model, pretrained, kwargs)
  File "RAM_test/recognize-anything/ram/models/utils.py", line 258, in load_checkpoint_swinlarge
    raise RuntimeError('checkpoint url or path is invalid')
RuntimeError: checkpoint url or path is invalid

**Comment by narchitect** [comment]
@wkrrya hi, may i ask you how to fix this error? I'm having the same issue with you.
