### ISSUE TITLE
Error while running inference_ram_plus.py

### ISSUE THREAD

**Issue by Pranavk02** [xinyu1205/recognize-anything#169]
After installing the package in different venv, I ran inference_ram_plus.py file and faced this error:

`Traceback (most recent call last):
  File "/Users/pranavkumar/Desktop/py-image-tag/main.py", line 43, in <module>
    model = ram_plus(pretrained=args.pretrained,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pranavkumar/anaconda3/envs/imgageTag/lib/python3.11/site-packages/ram/models/ram_plus.py", line 398, in ram_plus
    model, msg = load_checkpoint_swinlarge(model, pretrained, kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pranavkumar/anaconda3/envs/imgageTag/lib/python3.11/site-packages/ram/models/utils.py", line 258, in load_checkpoint_swinlarge
    raise RuntimeError('checkpoint url or path is invalid')
RuntimeError: checkpoint url or path is invalid`

**Comment by Pranavk02** [comment]
Hi @xinyu1205

**Comment by adbmdp** [comment]
The error message "RuntimeError: checkpoint url or path is invalid" indicates that the code is unable to locate or load the pre-trained model weights (checkpoint) you're trying to use.

Did you download the pre-trained model weights here? https://github.com/xinyu1205/recognize-anything#toolbox-checkpoints


> I ran inference_ram_plus.py file

How?
Should ne like this:
```
python inference_ram_plus.py  --image images/demo/demo1.jpg \
--pretrained pretrained/ram_plus_swin_large_14m.pth
```
