### ISSUE TITLE
missing dependency for clip

### ISSUE THREAD

**Issue by arsenyinfo** [xinyu1205/recognize-anything#38]
```
(.env) ➜  recognize-anything git:(main) ✗ python inference_ram_openset.py --image test_photos/dog.jpg --pretrained pretrained/ram_swin_large_14m.pth
Traceback (most recent call last):
  File "/Users/Arseny/dev/recognize-anything/inference_ram_openset.py", line 15, in <module>
    from models.openset_utils import build_openset_label_embedding
  File "/Users/Arseny/dev/recognize-anything/models/openset_utils.py", line 6, in <module>
    from clip import clip
ModuleNotFoundError: No module named 'clip'
```

Installing CLIP from `git+https://github.com/openai/CLIP.git` helps though.

**Comment by xinyu1205** [comment]
Thank you for your friendly and valuable feedback! I will fix it soon.

**Comment by Miles-Ma** [comment]
This is now fixed.
