### ISSUE TITLE
Image sizes

### ISSUE THREAD

**Issue by shersoni610** [xinyu1205/recognize-anything#62]
Hello,

what image sizes are supported by ram and tag2text models?

**Comment by xinyu1205** [comment]
Hi, the default input size is 384, and you can also specify the input size at will when model initialization.

**Comment by shersoni610** [comment]
Hello Xinyu,

After looking at the code it seems only two sizes are suported 224 and 384 and there is assert statement to check the image size. How should we handle 2k or 4K images?

**Comment by shersoni610** [comment]
This is error message with RAM:
(ramrecog) $ python inference_ram.py --image ~/Downloads/dot-and-mom-aziza-2-649f050319cb3.jpg --image-size 1024
Traceback (most recent call last):
  File "/Users/Projects/SegmentAnything/RAM/recognize-anything/inference_ram.py", line 42, in <module>
    model = ram(pretrained=args.pretrained, image_size=args.image_size, vit='swin_l')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Projects/SegmentAnything/RAM/recognize-anything/ram/models/ram.py", line 263, in ram
    model = RAM(**kwargs)
            ^^^^^^^^^^^^^
  File "/Users/Projects/SegmentAnything/RAM/recognize-anything/ram/models/ram.py", line 77, in __init__
    vision_config = read_json(vision_config_path)
                              ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'vision_config_path' where it is not associated with a value

**Comment by xinyu1205** [comment]
Hi, the reason should be that we only include the Swin config for 224&384 in ram/configs/swin. Perhaps you should check how Swin adapts to larger image resolutions.
