### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by aaronstru** [xinyu1205/recognize-anything#96]
Hey, thanks for your work. I get the following error when trying to use your model:
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/opt/conda/lib/python3.9/site-packages/typing_extensions.py)

Do you have any idea why?

Thanks in regard

**Comment by aaronstru** [comment]
This is the complete error message:

You selected RAM
You selected one image
Traceback (most recent call last):
  File "/home/jovyan/Daalman/recognize-anything/recognize-anything/inference_ram.py", line 9, in <module>
    import torch
  File "/opt/conda/lib/python3.9/site-packages/torch/__init__.py", line 1429, in <module>
    from torch import optim as optim
  File "/opt/conda/lib/python3.9/site-packages/torch/optim/__init__.py", line 8, in <module>
    from .adadelta import Adadelta
  File "/opt/conda/lib/python3.9/site-packages/torch/optim/adadelta.py", line 4, in <module>
    from .optimizer import (Optimizer, _use_grad_for_differentiable, _default_to_fused_or_foreach,
  File "/opt/conda/lib/python3.9/site-packages/torch/optim/optimizer.py", line 23, in <module>
    from typing_extensions import ParamSpec, Self, TypeAlias
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/opt/conda/lib/python3.9/site-packages/typing_extensions.py)

**Comment by xinyu1205** [comment]
Hi, I haven't encountered your error, which seems to be caused by your pytorch environment.
Maybe you can refer to this solution?
https://stackoverflow.com/questions/72980064/from-typing-extensions-import-paramspec-importerror-cannot-import-name-paramsp
